apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableAutoMtls: true
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.containers.[name:istio-proxy].ports
                  value:
                    - containerPort: 8080
                      hostPort: 8080
                      protocol: TCP
                    - containerPort: 8443
                      hostPort: 8443
                      protocol: TCP
