kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 8443
    hostPort: 8443
    listenAddress: "127.0.0.1"
  extraMounts:
   - hostPath: ../../
     containerPath: /host
     readOnly: true
